# -*- coding: utf-8 -*-
"""M1 - Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BwDPgqX0tdYLR_a3E6ltWTSYFVMKXBj

#Calculadora Módulo 1 Análise de Dados
"""

# Pede o nome do usuário
nome = input(('Digite seu nome: '))
print('Olá', nome, 'vamos fazer uma calculadora?')

# Pede para o usuário digitar dois números separadamente e depois escolher um operador
num1 = int(input('Digite um número de 0 a 10: '))
num2 = int(input('Agora, digite outro número de 0 a 10: '))
operador = input('Qual operação você quer fazer? (+, -, *, /): ')

# Se operador válido o programa soma, subtrai, multiplica ou divide, senão, avisa e pede operador válido
if operador == '+':
  soma = num1 + num2
  print(nome, 'a soma de', num1, '+', num2, 'é:', soma)
elif operador == '-':
  subtracao = num1 - num2
  print(nome, 'a subtração de', num1, '-', num2, 'é:', subtracao)
elif operador == '*':
  multi = num1 * num2
  print(nome, 'a multiplicação de',num1, '*', num2, 'é:', multi)
elif operador == '/':
  divisao = num1 // num2
  print(nome, 'a divisão', num1, '-', num2, 'é:', divisao)
else:
  print('Por favor digite um operador válido (+, -, *, /)')